FROM debian:11-slim

RUN apt-get update && apt-get install -y openjdk-17-jdk maven

COPY ./demo /app

WORKDIR /app

CMD ["mvn", "clean", "install", "-DskipTests", "exec:java", "-Dexec.mainClass=com.example.demo.DemoApplication"]

EXPOSE 8080